apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spaced-repetition
  name: spaced-repetition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spaced-repetition
  template:
    metadata:
      labels:
        app: spaced-repetition
    spec:
      containers:
        - name: spaced-repetition
          image: ivanovdv/spaced-repetition:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: spaced-repetition-env
